/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx}"],
  safelist: [
    'theme-emerald', 'theme-purple', 'theme-rose',
    'bg-green-100', 'text-green-700', 'bg-red-100', 'text-red-700',
    'bg-yellow-100', 'text-yellow-700', 'bg-blue-100', 'text-blue-700',
    'bg-purple-100', 'text-purple-700', 'bg-orange-100', 'text-orange-700',
    'bg-blue-50', 'bg-green-50', 'bg-red-50', 'bg-purple-50', 'bg-orange-50', 'bg-teal-50', 'bg-gray-50',
    'bg-blue-500', 'bg-green-500', 'bg-red-500', 'bg-purple-500', 'bg-orange-500', 'bg-teal-500', 'bg-gray-400',
    'border-blue-400', 'border-green-400', 'border-red-400', 'border-purple-400', 'border-orange-400', 'border-teal-400', 'border-gray-300',
    'bg-blue-50', 'bg-yellow-50', 'bg-green-50', 'bg-red-50', 'bg-purple-50',
    'border-blue-200', 'border-yellow-200', 'border-green-200', 'border-red-200', 'border-purple-200',
    'text-blue-700', 'text-yellow-700', 'text-green-700', 'text-red-700', 'text-purple-700',
    'text-blue-500', 'text-yellow-500', 'text-green-500', 'text-red-500', 'text-purple-500',
    'border-l-blue-500', 'border-l-red-500', 'border-l-amber-500', 'border-l-emerald-500', 'border-l-purple-500', 'border-l-slate-300',
    'bg-blue-50', 'bg-red-50', 'bg-amber-50', 'bg-emerald-50', 'bg-purple-50', 'bg-slate-50',
    'text-blue-600', 'text-red-600', 'text-amber-600', 'text-emerald-600', 'text-purple-600', 'text-slate-500',
    'text-blue-700', 'text-red-700', 'text-amber-700', 'text-emerald-700', 'text-purple-700',
    'bg-amber-100', 'text-amber-700', 'bg-slate-100', 'text-slate-600', 'bg-orange-100', 'text-orange-600',
    'bg-red-100', 'bg-emerald-50', 'bg-blue-50', 'bg-amber-50', 'bg-purple-50',
    'bg-teal-50', 'bg-teal-100', 'text-teal-500', 'text-teal-700', 'border-teal-300',
    'bg-orange-50', 'border-orange-300', 'border-green-300', 'border-yellow-300', 'border-red-300',
  ],
  theme: {
    extend: {
      fontFamily: {
        inter: ['var(--font-inter)'],
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: { DEFAULT: 'hsl(var(--card))', foreground: 'hsl(var(--card-foreground))' },
        popover: { DEFAULT: 'hsl(var(--popover))', foreground: 'hsl(var(--popover-foreground))' },
        primary: { DEFAULT: 'hsl(var(--primary))', foreground: 'hsl(var(--primary-foreground))' },
        secondary: { DEFAULT: 'hsl(var(--secondary))', foreground: 'hsl(var(--secondary-foreground))' },
        muted: { DEFAULT: 'hsl(var(--muted))', foreground: 'hsl(var(--muted-foreground))' },
        accent: { DEFAULT: 'hsl(var(--accent))', foreground: 'hsl(var(--accent-foreground))' },
        destructive: { DEFAULT: 'hsl(var(--destructive))', foreground: 'hsl(var(--destructive-foreground))' },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        success: { DEFAULT: 'hsl(var(--success))', foreground: 'hsl(var(--success-foreground))' },
        warning: { DEFAULT: 'hsl(var(--warning))', foreground: 'hsl(var(--warning-foreground))' },
        info: { DEFAULT: 'hsl(var(--info))', foreground: 'hsl(var(--info-foreground))' },
        chart: {
          '1': 'hsl(var(--chart-1))',
          '2': 'hsl(var(--chart-2))',
          '3': 'hsl(var(--chart-3))',
          '4': 'hsl(var(--chart-4))',
          '5': 'hsl(var(--chart-5))',
        },
        sidebar: {
          DEFAULT: 'hsl(var(--sidebar-background))',
          foreground: 'hsl(var(--sidebar-foreground))',
          primary: 'hsl(var(--sidebar-primary))',
          'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
          accent: 'hsl(var(--sidebar-accent))',
          'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
          border: 'hsl(var(--sidebar-border))',
          ring: 'hsl(var(--sidebar-ring))',
        },
      },
      keyframes: {
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up': { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}