// Map LINE emoticon text to Unicode emoji
const LINE_EMOJI_MAP = {
  '(hands together)': '🙏',
  '(happy)': '😄',
  '(sad)': '😢',
  '(angry)': '😠',
  '(love)': '❤️',
  '(heart)': '❤️',
  '(laugh)': '😂',
  '(cry)': '😭',
  '(wink)': '😉',
  '(kiss)': '😘',
  '(tongue)': '😛',
  '(surprised)': '😲',
  '(cool)': '😎',
  '(sleepy)': '😴',
  '(sweat)': '😅',
  '(shy)': '😊',
  '(blush)': '☺️',
  '(thinking)': '🤔',
  '(clap)': '👏',
  '(thumbsup)': '👍',
  '(thumbsdown)': '👎',
  '(ok)': '👌',
  '(peace)': '✌️',
  '(wave)': '👋',
  '(pray)': '🙏',
  '(muscle)': '💪',
  '(fire)': '🔥',
  '(star)': '⭐',
  '(sun)': '☀️',
  '(moon)': '🌙',
  '(rain)': '🌧️',
  '(snow)': '❄️',
  '(cloud)': '☁️',
  '(rainbow)': '🌈',
  '(gift)': '🎁',
  '(cake)': '🎂',
  '(coffee)': '☕',
  '(beer)': '🍺',
  '(music)': '🎵',
  '(phone)': '📞',
  '(mail)': '✉️',
  '(camera)': '📷',
  '(book)': '📖',
  '(money)': '💰',
  '(clock)': '⏰',
  '(check)': '✅',
  '(cross)': '❌',
  '(warning)': '⚠️',
  '(question)': '❓',
  '(exclamation)': '❗',
  '(sparkles)': '✨',
  '(party)': '🎉',
  '(100)': '💯',
  '(poop)': '💩',
  '(ghost)': '👻',
  '(skull)': '💀',
  '(alien)': '👽',
  '(robot)': '🤖',
  '(cat)': '🐱',
  '(dog)': '🐶',
  '(bear)': '🐻',
  '(pig)': '🐷',
  '(monkey)': '🐵',
  '(chicken)': '🐔',
  '(penguin)': '🐧',
  '(flower)': '🌸',
  '(rose)': '🌹',
  '(tree)': '🌳',
  '(leaf)': '🍃',
  '(cherry blossom)': '🌸',
  '(four leaf clover)': '🍀',
  '(broken heart)': '💔',
  '(two hearts)': '💕',
  '(sparkling heart)': '💖',
  '(heartbeat)': '💓',
  '(revolving hearts)': '💞',
  '(arrow heart)': '💘',
  '(blue heart)': '💙',
  '(green heart)': '💚',
  '(yellow heart)': '💛',
  '(purple heart)': '💜',
  '(black heart)': '🖤',
  '(white heart)': '🤍',
  '(smile)': '😊',
  '(grin)': '😁',
  '(joy)': '😂',
  '(rofl)': '🤣',
  '(relaxed)': '☺️',
  '(yum)': '😋',
  '(sunglasses)': '😎',
  '(heart eyes)': '😍',
  '(kissing heart)': '😘',
  '(stuck out tongue)': '😛',
  '(flushed)': '😳',
  '(dizzy)': '😵',
  '(rage)': '😡',
  '(triumph)': '😤',
  '(sob)': '😭',
  '(fearful)': '😨',
  '(cold sweat)': '😰',
  '(persevere)': '😣',
  '(disappointed)': '😞',
  '(confounded)': '😖',
  '(tired)': '😫',
  '(weary)': '😩',
  '(scream)': '😱',
  '(astonished)': '😲',
  '(hushed)': '😯',
  '(expressionless)': '😑',
  '(unamused)': '😒',
  '(neutral)': '😐',
  '(confused)': '😕',
  '(innocent)': '😇',
  '(smirk)': '😏',
  '(relieved)': '😌',
  '(pensive)': '😔',
  '(sleeping)': '😴',
  '(drool)': '🤤',
  '(mask)': '😷',
  '(nauseated)': '🤢',
  '(sneezing)': '🤧',
  '(hot)': '🥵',
  '(cold)': '🥶',
  '(woozy)': '🥴',
  '(zany)': '🤪',
  '(shushing)': '🤫',
  '(zipper mouth)': '🤐',
  '(monocle)': '🧐',
  '(nerd)': '🤓',
  '(devil)': '😈',
  '(angel)': '😇',
  '(eyes)': '👀',
  '(tongue out)': '😜',
  '(upside down)': '🙃',
  '(money mouth)': '🤑',
  '(hugging)': '🤗',
  '(hand over mouth)': '🤭',
  '(yawning)': '🥱',
  '(pleading)': '🥺',
  '(partying)': '🥳',
  '(smiling with tear)': '🥲',
};

export function replaceLineEmojis(text) {
  if (!text) return text;
  let result = text;
  for (const [pattern, emoji] of Object.entries(LINE_EMOJI_MAP)) {
    // Case-insensitive replacement
    const escaped = pattern.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    result = result.replace(new RegExp(escaped, 'gi'), emoji);
  }
  return result;
}