import { createClientFromRequest } from 'npm:@base44/sdk@0.8.23';

const TEMPLATES = [
  {
    template_code: 'TPL-PP30',
    name: 'ภ.พ.30 รายเดือน',
    description: 'งานยื่น ภ.พ.30 ประจำเดือน',
    match_type: 'obligation',
    obligation_type: 'pp30_monthly',
    service_type: 'accounting',
    department: 'accounting',
    recurring_type: 'monthly',
    due_date_rule: 15,
    estimated_days: 10,
    default_priority: 'medium',
    default_status: 'pending',
    default_owner_type: 'from_customer',
    status: 'active',
    default_checklist: [
      { item: '📢 ได้รับเอกสารจากลูกค้าแล้ว', checked: false },
      { item: 'ตรวจสอบรายการซื้อ-ขาย', checked: false },
      { item: 'กระทบยอด bank statement', checked: false },
      { item: '📢 ตรวจสอบเอกสารเสร็จแล้ว', checked: false },
      { item: '📢 รอ confirm ตัวเลข ภ.พ.30', checked: false },
      { item: 'อัพโหลดข้อมูลเข้า Peak', checked: false },
      { item: '📢 ยื่น ภ.พ.30', checked: false },
      { item: '📢 ชำระ ภ.พ.30 แล้ว', checked: false },
    ],
  },
  {
    template_code: 'TPL-PND3',
    name: 'ภ.ง.ด.3 รายเดือน',
    description: 'งานยื่น ภ.ง.ด.3 ประจำเดือน',
    match_type: 'obligation',
    obligation_type: 'pnd3_monthly',
    service_type: 'accounting',
    department: 'accounting',
    recurring_type: 'monthly',
    due_date_rule: 7,
    estimated_days: 5,
    default_priority: 'medium',
    default_status: 'pending',
    default_owner_type: 'from_customer',
    status: 'active',
    default_checklist: [
      { item: '📢 ได้รับเอกสารจากลูกค้าแล้ว', checked: false },
      { item: 'ตรวจสอบหนังสือรับรองหัก ณ ที่จ่าย', checked: false },
      { item: '📢 ตรวจสอบเอกสารเสร็จแล้ว', checked: false },
      { item: '📢 รอ confirm ตัวเลข ภ.ง.ด.3', checked: false },
      { item: '📢 ยื่น ภ.ง.ด.3', checked: false },
      { item: '📢 ชำระ ภ.ง.ด.3 แล้ว', checked: false },
    ],
  },
  {
    template_code: 'TPL-PND53',
    name: 'ภ.ง.ด.53 รายเดือน',
    description: 'งานยื่น ภ.ง.ด.53 ประจำเดือน',
    match_type: 'obligation',
    obligation_type: 'pnd53_monthly',
    service_type: 'accounting',
    department: 'accounting',
    recurring_type: 'monthly',
    due_date_rule: 7,
    estimated_days: 5,
    default_priority: 'medium',
    default_status: 'pending',
    default_owner_type: 'from_customer',
    status: 'active',
    default_checklist: [
      { item: '📢 ได้รับเอกสารจากลูกค้าแล้ว', checked: false },
      { item: 'ตรวจสอบหนังสือรับรองหัก ณ ที่จ่าย', checked: false },
      { item: '📢 ตรวจสอบเอกสารเสร็จแล้ว', checked: false },
      { item: '📢 รอ confirm ตัวเลข ภ.ง.ด.53', checked: false },
      { item: '📢 ยื่น ภ.ง.ด.53', checked: false },
      { item: '📢 ชำระ ภ.ง.ด.53 แล้ว', checked: false },
    ],
  },
  {
    template_code: 'TPL-PND54',
    name: 'ภ.ง.ด.54 รายเดือน',
    description: 'งานยื่น ภ.ง.ด.54 ประจำเดือน',
    match_type: 'obligation',
    obligation_type: 'pnd54_monthly',
    service_type: 'accounting',
    department: 'accounting',
    recurring_type: 'monthly',
    due_date_rule: 15,
    estimated_days: 5,
    default_priority: 'medium',
    default_status: 'pending',
    default_owner_type: 'from_customer',
    status: 'active',
    default_checklist: [
      { item: '📢 ได้รับเอกสารจากลูกค้าแล้ว', checked: false },
      { item: '📢 ตรวจสอบเอกสารเสร็จแล้ว', checked: false },
      { item: '📢 รอ confirm ตัวเลข ภ.ง.ด.54', checked: false },
      { item: '📢 ยื่น ภ.ง.ด.54', checked: false },
      { item: '📢 ชำระ ภ.ง.ด.54 แล้ว', checked: false },
    ],
  },
  {
    template_code: 'TPL-PP36',
    name: 'ภ.พ.36 รายเดือน',
    description: 'งานยื่น ภ.พ.36 ประจำเดือน',
    match_type: 'obligation',
    obligation_type: 'pp36_monthly',
    service_type: 'accounting',
    department: 'accounting',
    recurring_type: 'monthly',
    due_date_rule: 15,
    estimated_days: 5,
    default_priority: 'medium',
    default_status: 'pending',
    default_owner_type: 'from_customer',
    status: 'active',
    default_checklist: [
      { item: '📢 ได้รับเอกสารจากลูกค้าแล้ว', checked: false },
      { item: '📢 ตรวจสอบเอกสารเสร็จแล้ว', checked: false },
      { item: '📢 รอ confirm ตัวเลข ภ.พ.36', checked: false },
      { item: '📢 ยื่น ภ.พ.36', checked: false },
      { item: '📢 ชำระ ภ.พ.36 แล้ว', checked: false },
    ],
  },
  {
    template_code: 'TPL-PND1',
    name: 'ภ.ง.ด.1 รายเดือน',
    description: 'งานยื่น ภ.ง.ด.1 ประจำเดือน',
    match_type: 'obligation',
    obligation_type: 'pnd1_monthly',
    service_type: 'payroll',
    department: 'accounting',
    recurring_type: 'monthly',
    due_date_rule: 7,
    estimated_days: 5,
    default_priority: 'medium',
    default_status: 'pending',
    default_owner_type: 'from_customer',
    status: 'active',
    default_checklist: [
      { item: '📢 ได้รับเอกสารจากลูกค้าแล้ว', checked: false },
      { item: 'คำนวณเงินเดือน-ค่าจ้าง', checked: false },
      { item: '📢 ตรวจสอบเอกสารเสร็จแล้ว', checked: false },
      { item: '📢 รอ confirm ตัวเลข ภ.ง.ด.1', checked: false },
      { item: '📢 ยื่น ภ.ง.ด.1', checked: false },
      { item: '📢 ชำระ ภ.ง.ด.1 แล้ว', checked: false },
    ],
  },
  {
    template_code: 'TPL-SSO',
    name: 'ประกันสังคม รายเดือน',
    description: 'งานยื่นประกันสังคมประจำเดือน',
    match_type: 'obligation',
    obligation_type: 'sso_monthly',
    service_type: 'payroll',
    department: 'accounting',
    recurring_type: 'monthly',
    due_date_rule: 15,
    estimated_days: 5,
    default_priority: 'medium',
    default_status: 'pending',
    default_owner_type: 'from_customer',
    status: 'active',
    default_checklist: [
      { item: '📢 ได้รับเอกสารจากลูกค้าแล้ว', checked: false },
      { item: 'คำนวณเงินสมทบประกันสังคม', checked: false },
      { item: '📢 ตรวจสอบเอกสารเสร็จแล้ว', checked: false },
      { item: '📢 ยื่นประกันสังคม', checked: false },
      { item: '📢 ชำระประกันสังคมแล้ว', checked: false },
    ],
  },
  {
    template_code: 'TPL-ACCT-MONTHLY',
    name: 'บัญชีรายเดือน (ปิดบัญชี)',
    description: 'งานปิดบัญชีประจำเดือน',
    match_type: 'service',
    service_type: 'accounting',
    department: 'accounting',
    recurring_type: 'monthly',
    due_date_rule: 20,
    estimated_days: 15,
    default_priority: 'medium',
    default_status: 'pending',
    default_owner_type: 'from_customer',
    status: 'active',
    default_checklist: [
      { item: '📢 ได้รับเอกสารจากลูกค้าแล้ว', checked: false },
      { item: 'บันทึกรายการซื้อ', checked: false },
      { item: 'บันทึกรายการขาย', checked: false },
      { item: 'บันทึกรายการจ่าย', checked: false },
      { item: 'บันทึกรายการรับ', checked: false },
      { item: 'กระทบยอดธนาคาร', checked: false },
      { item: '📢 กำลังดำเนินการตรวจสอบเอกสาร', checked: false },
      { item: 'ตรวจสอบงบทดลอง', checked: false },
      { item: '📢 ปิดบัญชีเดือนนี้เสร็จแล้ว', checked: false },
    ],
  },
];

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (user?.role !== 'admin') {
      return Response.json({ error: 'Forbidden: Admin access required' }, { status: 403 });
    }

    const results = [];
    for (const tmpl of TEMPLATES) {
      const created = await base44.asServiceRole.entities.TaskTemplate.create(tmpl);
      results.push({ code: tmpl.template_code, name: tmpl.name, id: created.id });
    }

    return Response.json({
      success: true,
      message: `Created ${results.length} tax templates`,
      templates: results,
    });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});