import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  th: {
    // App
    app_name: 'ACC Consulting',
    app_subtitle: 'ระบบจัดการงาน',
    loading: 'กำลังโหลด...',
    saving: 'กำลังบันทึก...',
    save: 'บันทึก',
    cancel: 'ยกเลิก',
    add: 'เพิ่ม',
    edit: 'แก้ไข',
    delete: 'ลบ',
    search: 'ค้นหา...',
    no_data: 'ไม่พบข้อมูล',
    all: 'ทั้งหมด',
    confirm: 'ยืนยัน',
    back: 'กลับ',
    // Sidebar
    menu_dashboard: 'แดชบอร์ด',
    menu_tasks: 'จัดการงาน',
    menu_schedule: 'ตารางกิจกรรม',
    menu_customers: 'ลูกค้า',
    menu_templates: 'เทมเพลตงาน',
    menu_peak: 'Peak Account',
    menu_billing: 'Billing',
    menu_notifications: 'แจ้งเตือน',
    menu_line_chat: 'Line OA Chat',
    menu_reports: 'รายงาน',
    menu_users: 'จัดการผู้ใช้',
    menu_roles: 'สิทธิ์การใช้งาน',
    menu_audit: 'Audit Log',
    menu_settings: 'ตั้งค่า',
    collapse_menu: 'ย่อเมนู',
    // TopBar
    my_account: 'บัญชีของฉัน',
    theme_settings: 'ตั้งค่าธีม',
    settings: 'ตั้งค่า',
    logout: 'ออกจากระบบ',
    // Dashboard
    dashboard_title: 'แดชบอร์ด',
    dashboard_subtitle: 'ภาพรวมระบบ ACC Consulting',
    active_tasks: 'งานที่ดำเนินการ',
    customers: 'ลูกค้า',
    overdue: 'เกินกำหนด',
    unpaid: 'ค้างชำระ',
    task_status: 'สถานะงาน',
    due_date_alerts: 'แจ้งเตือน Due Date',
    recent_tasks: 'งานล่าสุด',
    no_alerts: 'ไม่มีงานใกล้กำหนด',
    overdue_days: 'เกิน {n} วัน',
    in_3days: 'อีก 3 วัน',
    in_7days: 'อีก 7 วัน',
    // Tasks
    tasks_title: 'จัดการงาน',
    tasks_subtitle: 'Task Management',
    create_task: 'สร้างงานใหม่',
    edit_task: 'แก้ไขงาน',
    search_tasks: 'ค้นหางาน...',
    task_name: 'ชื่องาน',
    customer: 'ลูกค้า',
    select_customer: 'เลือกลูกค้า',
    service_type: 'ประเภทบริการ',
    select_service: 'เลือกบริการ',
    assigned_to: 'ผู้รับผิดชอบ',
    select_assignee: 'เลือกผู้รับผิดชอบ',
    department: 'แผนก',
    select_department: 'เลือกแผนก',
    priority: 'ความสำคัญ',
    status: 'สถานะ',
    start_date: 'วันเริ่มงาน',
    due_date: 'กำหนดส่ง',
    description: 'รายละเอียด',
    checklist: 'รายการตรวจสอบ',
    add_item: 'เพิ่มรายการ...',
    update: 'อัปเดต',
    create: 'สร้างงาน',
    // Status
    status_pending: 'รอดำเนินการ',
    status_in_progress: 'กำลังทำ',
    status_review: 'รอตรวจสอบ',
    status_completed: 'เสร็จแล้ว',
    status_cancelled: 'ยกเลิก',
    status_active: 'ใช้งาน',
    status_inactive: 'ไม่ใช้งาน',
    status_suspended: 'ระงับ',
    status_draft: 'ร่าง',
    status_sent: 'ส่งแล้ว',
    status_paid: 'ชำระแล้ว',
    status_overdue: 'เกินกำหนด',
    status_scheduled: 'กำหนดแล้ว',
    // Priority
    priority_low: 'ต่ำ',
    priority_medium: 'ปานกลาง',
    priority_high: 'สูง',
    priority_urgent: 'เร่งด่วน',
    // Services
    service_accounting: 'ทำบัญชี',
    service_payroll: 'เงินเดือน',
    service_tax: 'ที่ปรึกษาภาษี',
    service_audit: 'ตรวจสอบบัญชี',
    service_peak: 'Peak Account',
    // Departments
    dept_management: 'Management',
    dept_accounting: 'บัญชี',
    dept_consulting: 'ที่ปรึกษา',
    dept_audit: 'Audit',
    dept_billing: 'Billing',
    dept_it: 'IT',
    // Customers
    customers_title: 'ลูกค้า',
    customers_subtitle: 'Customer Master',
    companies: 'บริษัท',
    add_customer: 'เพิ่มลูกค้า',
    edit_customer: 'แก้ไขข้อมูลลูกค้า',
    company_name_th: 'ชื่อบริษัท (ไทย)',
    company_name_en: 'ชื่อบริษัท (อังกฤษ)',
    tax_id: 'เลขผู้เสียภาษี',
    address: 'ที่อยู่',
    contact_person: 'ผู้ติดต่อ',
    email: 'อีเมล',
    phone: 'เบอร์โทร',
    services_used: 'บริการที่ใช้',
    notes: 'หมายเหตุ',
    // Schedule
    schedule_title: 'ตารางงาน',
    schedule_subtitle: 'Monthly Schedule',
    add_schedule: 'เพิ่มตารางงาน',
    title: 'หัวข้อ',
    date: 'วันที่',
    time_start: 'เวลาเริ่ม',
    time_end: 'เวลาสิ้นสุด',
    type: 'ประเภท',
    type_meeting: 'ประชุม',
    type_deadline: 'กำหนดส่ง',
    type_appointment: 'นัดหมาย',
    type_reminder: 'เตือนความจำ',
    type_other: 'อื่นๆ',
    no_schedule: 'ไม่มีตารางงานวันนี้',
    more: 'เพิ่มเติม',
    day_names: ['อา', 'จ', 'อ', 'พ', 'พฤ', 'ศ', 'ส'],
    // Peak Account
    peak_title: 'Licensing Peak Account',
    peak_subtitle: 'จัดการ Peak Account License',
    peak_total: 'ทั้งหมด',
    peak_expiring: 'ใกล้หมดอายุ',
    peak_expired: 'หมดอายุแล้ว',
    peak_start: 'เริ่ม',
    peak_end: 'หมดอายุ',
    no_peak: 'ไม่มีลูกค้าที่ใช้ Peak Account',
    days_left: 'อีก {n} วัน',
    // Billing
    billing_title: 'Billing & Payment',
    billing_subtitle: 'จัดการใบแจ้งหนี้และการชำระเงิน',
    create_invoice: 'สร้างใบแจ้งหนี้',
    total_paid: 'ชำระแล้วทั้งหมด',
    total_pending: 'ค้างชำระ',
    total_invoices: 'จำนวนใบแจ้งหนี้',
    invoice_number: 'เลขที่ใบแจ้งหนี้',
    amount: 'จำนวนเงิน',
    due_payment: 'กำหนดชำระ',
    service: 'บริการ',
    // Notifications
    notif_title: 'แจ้งเตือน',
    notif_unread: '{n} รายการยังไม่อ่าน',
    mark_all_read: 'อ่านทั้งหมด',
    no_notifications: 'ไม่มีการแจ้งเตือน',
    notif_due_7days: 'อีก 7 วัน',
    notif_due_3days: 'อีก 3 วัน',
    notif_overdue: 'เกินกำหนด',
    notif_assigned: 'มอบหมายงาน',
    notif_completed: 'งานเสร็จ',
    notif_system: 'ระบบ',
    notif_billing: 'Billing',
    // Line Chat
    line_title: 'Line OA Chat',
    line_subtitle: 'รวมแชท Line OA',
    type_message: 'พิมพ์ข้อความ...',
    no_messages: 'ยังไม่มีข้อความ',
    select_chat: 'เลือกการสนทนา',
    // Templates
    templates_title: 'เทมเพลตงาน',
    templates_subtitle: 'Task Template & Recurring Task Planner',
    create_template: 'สร้างเทมเพลต',
    template_name: 'ชื่อเทมเพลต',
    recurring: 'งานประจำ',
    recurring_none: 'ไม่ประจำ',
    recurring_monthly: 'รายเดือน',
    recurring_quarterly: 'รายไตรมาส',
    recurring_yearly: 'รายปี',
    no_templates: 'ยังไม่มีเทมเพลต',
    items: 'รายการ',
    // Reports
    reports_title: 'รายงาน',
    reports_subtitle: 'Dashboard & Reporting',
    total_tasks: 'งานทั้งหมด',
    total_revenue: 'รายได้รวม',
    tasks_by_service: 'งานตามบริการ',
    revenue_by_service: 'รายได้ตามบริการ',
    // Users
    users_title: 'จัดการผู้ใช้',
    users_subtitle: 'User Master',
    people: 'คน',
    invite_user: 'เชิญผู้ใช้',
    invite_title: 'เชิญผู้ใช้ใหม่',
    send_invite: 'ส่งคำเชิญ',
    edit_user: 'แก้ไขข้อมูลผู้ใช้',
    name: 'ชื่อ',
    position: 'ตำแหน่ง',
    role: 'ตำแหน่ง',
    search_users: 'ค้นหาผู้ใช้...',
    // Roles
    roles_title: 'สิทธิ์การใช้งาน',
    roles_subtitle: 'User Role Management — กำหนดเมนูที่ผู้ใช้เข้าถึงได้',
    users_label: 'ผู้ใช้งาน',
    permissions_of: 'สิทธิ์ของ {name}',
    select_user: 'เลือกผู้ใช้เพื่อจัดการสิทธิ์',
    select_all: 'เลือกทั้งหมด',
    clear: 'ล้าง',
    admin_full_access: 'Admin / Management สามารถเข้าถึงทุกเมนูได้',
    save_permissions: 'บันทึกสิทธิ์',
    // Audit
    audit_title: 'Audit Log',
    audit_subtitle: 'บันทึกการเปลี่ยนแปลงระบบ',
    no_logs: 'ไม่มีบันทึก',
    // Settings
    settings_title: 'ตั้งค่า',
    settings_subtitle: 'ตั้งค่าส่วนตัวและธีม',
    choose_theme: 'เลือกธีมสี',
    notif_settings: 'การแจ้งเตือน',
    email_notif: 'แจ้งเตือนทาง Email',
    email_notif_desc: 'รับการแจ้งเตือน due date ผ่าน Gmail / Microsoft 365',
    line_notif: 'แจ้งเตือนทาง Line OA',
    line_notif_desc: 'รับการแจ้งเตือนผ่าน Line Official Account',
    language: 'ภาษา',
    language_desc: 'เลือกภาษาที่ต้องการใช้งาน',
    save_settings: 'บันทึกการตั้งค่า',
    saved: 'บันทึกแล้ว',
    // My Day
    menu_my_day: 'My Day',
    my_day_greeting_morning: 'สวัสดีตอนเช้า',
    my_day_greeting_afternoon: 'สวัสดีตอนบ่าย',
    my_day_greeting_evening: 'สวัสดีตอนเย็น',
    my_day_today_focus: 'งานวันนี้',
    my_day_overdue: 'งานเกินกำหนด',
    my_day_no_tasks: 'ไม่มีงานครบกำหนดวันนี้',
    my_day_stats: 'สถิติเดือนนี้',
    my_day_completed: 'งานเสร็จ',
    my_day_ontime: 'ส่งตรงเวลา',
    my_day_hours: 'เวลาทำงาน',
    my_day_streak: 'Streak',
    my_day_timer: 'จับเวลา',
    my_day_start_timer: 'เริ่มจับเวลา',
    my_day_stop_timer: 'หยุด',
    my_day_select_task: 'เลือกงาน...',
    my_day_feed: 'ข่าวสารบริษัท',
    my_day_shoutouts: 'ชมเชยล่าสุด',
    my_day_start_work: 'เริ่มทำ',
    my_day_send_review: 'ส่งตรวจ',
    my_day_mark_done: 'เสร็จ',
    my_day_overdue_days: 'เกิน {n} วัน',
    my_day_achievements: 'Achievements',
    my_day_shoutout_btn: 'ชมเชยเพื่อน',
    my_day_shoutout_to: 'ชมเชยใคร',
    my_day_shoutout_category: 'หมวดหมู่',
    my_day_shoutout_message: 'ข้อความชมเชย',
    my_day_shoutout_task: 'งานที่เกี่ยวข้อง (ไม่บังคับ)',
    my_day_shoutout_submit: 'ส่งชมเชย',
    my_day_shoutout_no_data: 'ยังไม่มีการชมเชย — เป็นคนแรกที่ชมเชยเพื่อนร่วมงาน!',
    my_day_shoutout_success: 'ส่งชมเชยเรียบร้อย!',
    // Role labels
    role_admin: 'Admin',
    role_management: 'Management',
    role_manager: 'Manager',
    role_super_supervisor: 'Super Supervisor',
    role_staff: 'Staff',
    // Accounting services full
    svc_accounting_full: 'รับทำบัญชี',
    svc_payroll_full: 'รับทำเงินเดือน',
    svc_tax_full: 'ที่ปรึกษาภาษีรายเดือน',
    svc_audit_full: 'งานตรวจสอบบัญชี',
    svc_peak_full: 'Licensing Peak Account',
  },
  en: {
    // My Day (English)
    menu_my_day: 'My Day',
    my_day_greeting_morning: 'Good morning',
    my_day_greeting_afternoon: 'Good afternoon',
    my_day_greeting_evening: 'Good evening',
    my_day_today_focus: "Today's Tasks",
    my_day_overdue: 'Overdue',
    my_day_no_tasks: 'No tasks due today',
    my_day_stats: 'This Month',
    my_day_completed: 'Completed',
    my_day_ontime: 'On Time',
    my_day_hours: 'Hours Logged',
    my_day_streak: 'Streak',
    my_day_timer: 'Timer',
    my_day_start_timer: 'Start Timer',
    my_day_stop_timer: 'Stop',
    my_day_select_task: 'Select task...',
    my_day_feed: 'Company Feed',
    my_day_shoutouts: 'Recent Shout-outs',
    my_day_start_work: 'Start',
    my_day_send_review: 'Review',
    my_day_mark_done: 'Done',
    my_day_overdue_days: '{n} days overdue',
    my_day_achievements: 'Achievements',
    my_day_shoutout_btn: 'Give Shout-out',
    my_day_shoutout_to: 'Who to recognize',
    my_day_shoutout_category: 'Category',
    my_day_shoutout_message: 'Your message',
    my_day_shoutout_task: 'Related task (optional)',
    my_day_shoutout_submit: 'Send Shout-out',
    my_day_shoutout_no_data: 'No shout-outs yet — be the first to recognize a colleague!',
    my_day_shoutout_success: 'Shout-out sent!',
    app_name: 'ACC Consulting',
    app_subtitle: 'Management System',
    loading: 'Loading...',
    saving: 'Saving...',
    save: 'Save',
    cancel: 'Cancel',
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    search: 'Search...',
    no_data: 'No data found',
    all: 'All',
    confirm: 'Confirm',
    back: 'Back',
    menu_dashboard: 'Dashboard',
    menu_tasks: 'Tasks',
    menu_schedule: 'Schedule',
    menu_customers: 'Customers',
    menu_templates: 'Templates',
    menu_peak: 'Peak Account',
    menu_billing: 'Billing',
    menu_notifications: 'Notifications',
    menu_line_chat: 'Line OA Chat',
    menu_reports: 'Reports',
    menu_users: 'Users',
    menu_roles: 'Permissions',
    menu_audit: 'Audit Log',
    menu_settings: 'Settings',
    collapse_menu: 'Collapse',
    my_account: 'My Account',
    theme_settings: 'Theme Settings',
    settings: 'Settings',
    logout: 'Logout',
    dashboard_title: 'Dashboard',
    dashboard_subtitle: 'ACC Consulting Overview',
    active_tasks: 'Active Tasks',
    customers: 'Customers',
    overdue: 'Overdue',
    unpaid: 'Unpaid',
    task_status: 'Task Status',
    due_date_alerts: 'Due Date Alerts',
    recent_tasks: 'Recent Tasks',
    no_alerts: 'No upcoming deadlines',
    overdue_days: '{n} days overdue',
    in_3days: 'In 3 days',
    in_7days: 'In 7 days',
    tasks_title: 'Task Management',
    tasks_subtitle: 'Manage all tasks',
    create_task: 'New Task',
    edit_task: 'Edit Task',
    search_tasks: 'Search tasks...',
    task_name: 'Task Name',
    customer: 'Customer',
    select_customer: 'Select customer',
    service_type: 'Service Type',
    select_service: 'Select service',
    assigned_to: 'Assigned To',
    select_assignee: 'Select assignee',
    department: 'Department',
    select_department: 'Select department',
    priority: 'Priority',
    status: 'Status',
    start_date: 'Start Date',
    due_date: 'Due Date',
    description: 'Description',
    checklist: 'Checklist',
    add_item: 'Add item...',
    update: 'Update',
    create: 'Create',
    status_pending: 'Pending',
    status_in_progress: 'In Progress',
    status_review: 'In Review',
    status_completed: 'Completed',
    status_cancelled: 'Cancelled',
    status_active: 'Active',
    status_inactive: 'Inactive',
    status_suspended: 'Suspended',
    status_draft: 'Draft',
    status_sent: 'Sent',
    status_paid: 'Paid',
    status_overdue: 'Overdue',
    status_scheduled: 'Scheduled',
    priority_low: 'Low',
    priority_medium: 'Medium',
    priority_high: 'High',
    priority_urgent: 'Urgent',
    service_accounting: 'Accounting',
    service_payroll: 'Payroll',
    service_tax: 'Tax Consulting',
    service_audit: 'Audit',
    service_peak: 'Peak Account',
    dept_management: 'Management',
    dept_accounting: 'Accounting',
    dept_consulting: 'Consulting',
    dept_audit: 'Audit',
    dept_billing: 'Billing',
    dept_it: 'IT',
    customers_title: 'Customers',
    customers_subtitle: 'Customer Master',
    companies: 'companies',
    add_customer: 'Add Customer',
    edit_customer: 'Edit Customer',
    company_name_th: 'Company Name (TH)',
    company_name_en: 'Company Name (EN)',
    tax_id: 'Tax ID',
    address: 'Address',
    contact_person: 'Contact Person',
    email: 'Email',
    phone: 'Phone',
    services_used: 'Services Used',
    notes: 'Notes',
    schedule_title: 'Schedule',
    schedule_subtitle: 'Monthly Schedule',
    add_schedule: 'Add Schedule',
    title: 'Title',
    date: 'Date',
    time_start: 'Start Time',
    time_end: 'End Time',
    type: 'Type',
    type_meeting: 'Meeting',
    type_deadline: 'Deadline',
    type_appointment: 'Appointment',
    type_reminder: 'Reminder',
    type_other: 'Other',
    no_schedule: 'No events today',
    more: 'more',
    day_names: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    peak_title: 'Peak Account Licensing',
    peak_subtitle: 'Manage Peak Account Licenses',
    peak_total: 'Total',
    peak_expiring: 'Expiring Soon',
    peak_expired: 'Expired',
    peak_start: 'Start',
    peak_end: 'Expires',
    no_peak: 'No Peak Account customers',
    days_left: '{n} days left',
    billing_title: 'Billing & Payment',
    billing_subtitle: 'Manage invoices and payments',
    create_invoice: 'New Invoice',
    total_paid: 'Total Paid',
    total_pending: 'Outstanding',
    total_invoices: 'Total Invoices',
    invoice_number: 'Invoice Number',
    amount: 'Amount',
    due_payment: 'Due Date',
    service: 'Service',
    notif_title: 'Notifications',
    notif_unread: '{n} unread',
    mark_all_read: 'Mark All Read',
    no_notifications: 'No notifications',
    notif_due_7days: 'In 7 days',
    notif_due_3days: 'In 3 days',
    notif_overdue: 'Overdue',
    notif_assigned: 'Assigned',
    notif_completed: 'Completed',
    notif_system: 'System',
    notif_billing: 'Billing',
    line_title: 'Line OA Chat',
    line_subtitle: 'Unified Line OA Chat',
    type_message: 'Type a message...',
    no_messages: 'No messages yet',
    select_chat: 'Select a conversation',
    templates_title: 'Task Templates',
    templates_subtitle: 'Task Template & Recurring Task Planner',
    create_template: 'New Template',
    template_name: 'Template Name',
    recurring: 'Recurring',
    recurring_none: 'None',
    recurring_monthly: 'Monthly',
    recurring_quarterly: 'Quarterly',
    recurring_yearly: 'Yearly',
    no_templates: 'No templates yet',
    items: 'items',
    reports_title: 'Reports',
    reports_subtitle: 'Dashboard & Reporting',
    total_tasks: 'Total Tasks',
    total_revenue: 'Total Revenue',
    tasks_by_service: 'Tasks by Service',
    revenue_by_service: 'Revenue by Service',
    users_title: 'User Management',
    users_subtitle: 'User Master',
    people: 'people',
    invite_user: 'Invite User',
    invite_title: 'Invite New User',
    send_invite: 'Send Invitation',
    edit_user: 'Edit User',
    name: 'Name',
    position: 'Position',
    role: 'Role',
    search_users: 'Search users...',
    roles_title: 'Permissions',
    roles_subtitle: 'User Role Management — Assign menu access',
    users_label: 'Users',
    permissions_of: 'Permissions for {name}',
    select_user: 'Select a user to manage permissions',
    select_all: 'Select All',
    clear: 'Clear',
    admin_full_access: 'Admin / Management has full access',
    save_permissions: 'Save Permissions',
    audit_title: 'Audit Log',
    audit_subtitle: 'System change history',
    no_logs: 'No logs found',
    settings_title: 'Settings',
    settings_subtitle: 'Personal settings and theme',
    choose_theme: 'Choose Theme',
    notif_settings: 'Notifications',
    email_notif: 'Email Notifications',
    email_notif_desc: 'Receive due date alerts via Gmail / Microsoft 365',
    line_notif: 'Line OA Notifications',
    line_notif_desc: 'Receive alerts via Line Official Account',
    language: 'Language',
    language_desc: 'Choose your preferred language',
    save_settings: 'Save Settings',
    saved: 'Saved',
    role_admin: 'Admin',
    role_management: 'Management',
    role_manager: 'Manager',
    role_super_supervisor: 'Super Supervisor',
    role_staff: 'Staff',
    svc_accounting_full: 'Accounting Services',
    svc_payroll_full: 'Payroll Services',
    svc_tax_full: 'Monthly Tax Consulting',
    svc_audit_full: 'Audit Services',
    svc_peak_full: 'Peak Account Licensing',
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('acc_lang') || 'th');

  useEffect(() => {
    localStorage.setItem('acc_lang', lang);
  }, [lang]);

  const t = (key, params) => {
    let text = translations[lang]?.[key] || translations['th']?.[key] || key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, v);
      });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}